### ISSUE TITLE
About theano

### ISSUE THREAD

**Issue by xuzhang5788** [pulimeng/eToxPred#2]
Is it must to use theano? Because theano will not get support anymore, so people use tensorflow  instead, especially for keras users. I read your code. You used theano for graph. Do you have alternatives? Many thanks.

**Comment by pulimeng** [comment]
Indeed since the model is built with theano. This project was developed before Tensorflow gets popular. I think there are quite many implementations of DBN with tensorflow or pytorch. For example, https://github.com/mehulrastogi/Deep-Belief-Network-pytorch/blob/master/DBN.py. All the utils we provided for the data preprocessing also works. However, if you only need the toxicity part. You do not need Theano at all cause that part is solely based on sklearn.
